version: '3.8'

services:
  postgres:
    image: postgres
    container_name: nextjs_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wedding
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nextjs_network

volumes:
  postgres_data: {}

networks:
  nextjs_network:
    driver: bridge
